name: 'Kittengrid'
description: 'Runs kittengrid agent'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/main.sh "pr-${{ github.event_name }}-${{ github.event.number }}"
      shell: bash
