name: 'Kittengrid'
description: 'Runs kittengrid agent'
runs:
  using: "composite"
  steps:
    - name: Setup Environment (PR)
      if: ${{ github.event_name == 'pull_request' }}
      run: echo "KITTENGRID_LAST_COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> ${GITHUB_ENV}
      shell: /usr/bin/bash -e {0}
    - if: ${{ !cancelled() }}
      run: ${{ github.action_path }}/main.sh --pull-request "${{ github.event.number }}" --repo "${{ github.repository }}"
      shell: /usr/bin/bash -e {0}
