name: 'Kittengrid'
description: 'Runs kittengrid agent'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/main.sh --pull-request "${{ github.event.number }}" --repo "${{ github.repository }}"
      shell: bash
