name: test-workflow
on: pull_request
jobs:
  magec-test:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - id: kittengrid-action
        uses: ./
        env:
          KITTENGRID_API_KEY: ${{ secrets.KITTENGRID_MAGEC_API_KEY }}
          KITTENGRID_API_URL: https://app.magec.kittengrid.com/
  # morantron-test:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     actions: write
  #     contents: read
  #   steps:
  #     - uses: actions/checkout@v3
  #     - id: kittengrid-action
  #       uses: ./
  #       env:
  #         KITTENGRID_API_KEY: ${{ secrets.KITTENGRID_MORANTRON_API_KEY }}
  #         KITTENGRID_API_URL: https://morantron.kittengrid.com/
